name: Linting and unit test

on:
  pull_request:
    branches: 
      - 'main'

jobs:
  build:
    name: linting and unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install flake8
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Run unit tests
      run: |
        pytest tests
    - name: Run linting tests
      run: | 
        flake8 --ignore F841 src/model/
