name: Train and Deploy

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-dev-mlops' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-dev-mlops' 
        type: string

jobs:
  Train:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default aml workspace
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}"
        az configure --defaults workspace="${{ github.event.inputs.aml_workspace }}"
    - name: Trigger Azure Machine Learning job
      run: |
        az ml job create --file src/job.yml  
  
  Register:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: [Train]
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default aml workspace
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}"
        az configure --defaults workspace="${{ github.event.inputs.aml_workspace }}"
    - name: Register model in AML
      run: |  
        JOB_NAME=$(az ml job list --resource-group rg-dev-mlops --workspace mlw-dev-mlops --query "[0].name" | tr -d '"')
        az ml model create --name "diabetes-model" --type "mlflow_model" --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model"
  
  Deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    needs: [Register]
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set default aml workspace
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}"
        az configure --defaults workspace="${{ github.event.inputs.aml_workspace }}"
    - name: Create an endpoint
      run: |
        export ENDPOINT_NAME="diabetes-mlflow-cl"
        az ml online-endpoint create --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops --name $ENDPOINT_NAME -f src/create-endpoint.yml
    - name: Deploy logged model to managed real-time endpoint
      run: |
        az ml online-deployment create --resource-group rg-dev-mlops --workspace-name mlw-dev-mlops --name mlflow-deployment --endpoint $ENDPOINT_NAME -f src/mlflow-deployment.yml --all-traffic